include $(srctree)/drivers/misc/mediatek/Makefile.custom
MTK_CUSTOM_PATH  := $(srctree)/drivers/misc/mediatek
ccflags-y += -I$(MTK_CUSTOM_PATH)/cam_cal/inc \
             -I$(MTK_CUSTOM_PATH)/imgsensor/inc \
             -I$(MTK_CUSTOM_PATH)/camera/$(MTK_PLATFORM)
obj-y += imx258_eeprom.o


